name: my first workflow

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: ACTION
            uses: actions/checkout@v4         
          - name: welcome message
            run: echo "message"
          - name: List Files
            run: ls 
          - name: show data
            run: cat README.md

