name: my first workflow

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: ACTION
            uses: actions/checkout@v4         
          - name: LIST and READ files
            run: |
              echo "message"
              ls -ltra
              cat README.md
              cat /etc/os-release > os-info.txt
          - name: upload file
            uses: actions/upload-artifact@v4
            with:
             name: os-text-file
             path: os-info.txt

    second_job:
      needs: first_job
      runs-on: ubuntu-latest
      steps:
        - name: whoami
          run: whoami
        - name: Download file
          uses: actions/download-artifact@v4
          with:
           name: os-text-file
    
    third_job:
      needs: second_job
      runs-on: ubuntu-latest
      steps:
        - name: Download file
          uses: actions/download-artifact@v4
          with:
           name: os-text-file-2
        - name: show file
          run: cat os-info.txt