name: my first workflow

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: ACTION
            uses: actions/checkout@v4         
          - name: LIST and READ files
            run: |
              echo "message"
              ls -ltra
              cat README.md
    second_job:
      needs: first_job
      runs-on: ubuntu-latest
      steps:
        - name: whoami
          run: whoami



