name: my first workflow

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: ACTION
            uses: actions/checkout@v4         
          - name: LIST and READ files
            run: |
              echo "message"
              ls-ltra
              cat README.md
          - name: Generate ASCII Artwork 
            run: cosway -f akash "Akash" >> akash.txt
                  


#          - name: List Files
#            run: ls 
#          - name: show data
#            run: cat README.md

