name: Exploring variables and secrets

on: push 

env: 
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-action-nginx

jobs:
    docker: 
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest 